### ISSUE TITLE
Bug #21700 cloud-init cant handle phone_home for mark instance is built

### ISSUE THREAD

**Issue by ghost** [theforeman/foreman_userdata#1]
In relation to a [old topic ](https://projects.theforeman.org/issues/15074) i think the phone_home does not work properly for setting a host instance is built automatically at cloud-init.

After a question on the[ mailing-list at foreman-users](https://groups.google.com/forum/#!topic/foreman-users/n3-TvTLpSDc) how the build token works, i paste following code in my user_data template for cloud-init at foreman-vmware.

`<%# Contact Foreman to confirm instance is built -%>
phone_home:
  url: <%= foreman_url('built') %>
  post: []
tries: 10`

When i review the user_data template after host-creation, i see the built?token-URL, but from the production.log it never arrives the foreman-instance. If i paste the built?token-URL in my browser, the Build status change from "pending installation" to "installed" and this is logged in the production log as expected. If i dont do that, the Build Status change from "pending installation" to "Token Expired" after a while.

Iam using this user_data template for provisioning windows server over foreman-vmware:
https://pastebin.com/gkFpTMpN

update: i create a bug ticket on the issue tracker here: http://projects.theforeman.org/issues/21700

**Comment by timogoebel** [comment]
@andpk:

Your template looks correct. This is what works for me with Linux.
Maybe this is a issue with Windows and cloud-init? Have you checked that the module is supported?
When you access the URL `http://your.foreman.example.com/userdata/user-data` from the cloud-init server, does it correctly show you the template?

```
#cloud-config
hostname: <%= @host.name %>
fqdn: <%= @host %>
manage_etc_hosts: true
users: {}
runcmd:
- |
<%= indent(2) { snippet('puppet_setup LXDM', :variables => { :full_puppet_run => true }) } %>

phone_home:
  url: <%= foreman_url('built') %>
  post: []
  tries: 10
```

**Comment by ghost** [comment]
@timogoebel 

Thanks for your fast reply and help. Did you meen with cloud-init-server the foreman instance? if i replace your.foreman.example.com with one of my foreman-master server, the page is unknown. I see my user-Data Template only from the host when i access the URL:

https://foreman.example.com/unattended/user_data?hostname=host.example.com

There is the phone_home: entry with the resolved build-token-"hash"

```
phone_home:
  url: http://foreman.example-com/unattended/built?token=dad9b32d-c3b9-4f2a-a96e-dcbd969ad698
  post: []
tries: 10
```

edit: i see, that my "tries:" has missing one space charachter ... maybe this is my problem (?). 
I will try and report.

edit2: still does not work. I didnt see any call in the production.log

**Comment by timogoebel** [comment]
> I see my user-Data Template only from the host when i access the URL:

This is, how this plugin is intended to work.

Have you checked cloud-init's log files on your host? You should see the call there. Have you activated the `phone_home` module in cloud-init? I have no knowledge about cloud-init on Windows, but I do suspect that the issue is there.

**Comment by ghost** [comment]
Thanks for your answer.

I didnt have activate the phone_home module in cloud init ... honestly, i dont know this is nescessary or better said i dont know a module with this name exists. I dont see any description in the 1.15 Documentation about a phone_home module.  I miss a explaniation about "Build Token" also ... How can activate this phone_home module? Seems like this really could be the problem.

**Comment by ghost** [comment]
having the same problem. the foreman_url or https://.../built?token=... does not work. i also tried http but then you have to set ssl untrusted to true or so in settings.yaml. i didnt wanted that so i put in the https:// instead of foreman_url. both dont work. confirmed on >5 hosts

2017-12-09 02:03:53,516 - util.py[WARNING]: /etc/ssh/ssh_host_dsa_key.pub: failed to open, can not phone home that data!
2017-12-09 02:03:53,516 - util.py[DEBUG]: /etc/ssh/ssh_host_dsa_key.pub: failed to open, can not phone home that data!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.py", line 111, in handle
    all_keys[n] = util.load_file(path)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1257, in load_file
    if decode:
IOError: [Errno 2] No such file or directory: '/etc/ssh/ssh_host_dsa_key.pub'
2017-12-09 02:03:53,519 - url_helper.py[DEBUG]: [0/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:03:58,542 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:01,543 - url_helper.py[DEBUG]: [1/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:06,553 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:09,556 - url_helper.py[DEBUG]: [2/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:14,564 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:17,568 - url_helper.py[DEBUG]: [3/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:22,576 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:25,580 - url_helper.py[DEBUG]: [4/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:30,588 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:33,592 - url_helper.py[DEBUG]: [5/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:38,600 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:41,601 - url_helper.py[DEBUG]: [6/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:46,609 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:49,613 - url_helper.py[DEBUG]: [7/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:04:54,623 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:04:57,626 - url_helper.py[DEBUG]: [8/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:05:02,636 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:05:05,639 - url_helper.py[DEBUG]: [9/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:05:10,647 - url_helper.py[DEBUG]: Please wait 3 seconds while we wait to try again
2017-12-09 02:05:13,649 - url_helper.py[DEBUG]: [10/11] open 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69' with {'url': 'https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69', 'headers': {'User-Agent': 'Cloud-Init/17.1'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
2017-12-09 02:05:18,660 - util.py[WARNING]: Failed to post phone home data to https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69 in 10 tries
2017-12-09 02:05:18,660 - util.py[DEBUG]: Failed to post phone home data to https://katello-proxy.inside.local:8000/unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69 in 10 tries
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.py", line 141, in handle
    ssl_details=util.fetch_ssl_details(cloud.paths))
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 892, in read_file_or_url
    len(blob), allowed)
  File "/usr/lib/python2.7/site-packages/cloudinit/url_helper.py", line 270, in readurl
    raise excps[-1]
UrlError: HTTPSConnectionPool(host='katello-proxy.inside.local', port=8000): Max retries exceeded with url: /unattended/built?token=1a3c5f00-3add-4cea-8b86-297f65d05e69 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x33dd710>, 'Connection to katello-proxy.inside.local timed out. (connect timeout=5.0)'))
2017-12-09 02:05:18,662 - handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home ran successfully

**Comment by timogoebel** [comment]
@ybaumy:
You should change the phone home to something like this:

```
phone_home:
  url: <%= foreman_url('built') %>
  post: []
  tries: 10
```
Pay attention to the `post: []` line. That should help you get rid of the `/etc/ssh/ssh_host_dsa_key.pub` warning.

Can you use curl to access the generated URL?
What I mean is the following: Please get the rendered url with token from the template preview, then post the output of

```
curl -vvv -D - https://foreman.example.com/unattended/built?token...
```

and the corresponding line with debug loglevel from /etc/foreman/production.log. If the rendered url is proxies via a foreman smart proxy, also check the logs there.

If you use https, make sure that the certificate is valid on the cloud-init client. You might need to add katello's ca certificate to the truststore.

```https://katello-proxy.inside.local:8000``` if this is a smart proxy, port 8000 usually is http / 8443 is https.

**Comment by ghost** [comment]
foreman_url is in my case the smart proxy.. it seems

http://qsc-katello-proxy.inside.local:8000/unattended/built?token=8026dd27-8345-4417-8a96-dd364b711781

do i need to install userdata on the proxy as well?

**Comment by ghost** [comment]
foreman_url is in my case the smart proxy.. it seems

http://qsc-katello-proxy.inside.local:8000/unattended/built?token=8026dd27-8345-4417-8a96-dd364b711781

do i need to install userdata on the proxy as well?

**Comment by timogoebel** [comment]
@ybaumy: No, you don't need a smart-proxy plugin. The build-call is a Foreman core feature. This should just work and has nothing to do with the userdata plugin.

Can you execute the following on the host that you just installed?

```
curl -vvv -D - http://qsc-katello-proxy.inside.local:8000/unattended/built?token=8026dd27-8345-4417-8a96-dd364b711781
```

and post the corresponding log from foreman and smart-proxy with both debug level logging enabled?
Make sure, the token is not expired.

**Comment by ghost** [comment]
sorry was busy doing other things.
it works now. the problem was the autosign of puppetca i guess because after that the registration with proxy worked and then the phone_home too.

**Comment by timogoebel** [comment]
@ybaumy: Thanks for reporting back. I'm glad, this is resolved now.
